"""
OpenEnv HTTP/WebSocket Server for the Inventory Clone Environment.

Uses OpenEnv's create_app() to auto-generate ALL server routes:
  - POST /reset        → Reset the environment
  - POST /step         → Execute an action
  - GET  /state        → Get current state
  - GET  /health       → Health check
  - WebSocket /ws      → Persistent WebSocket connection
  - GET  /schema       → Action/Observation JSON schemas
  - GET  /             → Web UI (auto-generated by OpenEnv)

Usage (from the inventory_clone/ folder):
    Local:  uv run server
    Docker: docker run -p 9000:9000 openenv-inventory-clone
"""

import sys
from pathlib import Path
from typing import Any, Union

from pydantic import TypeAdapter

from openenv.core.env_server.http_server import create_app
from openenv.core.env_server.mcp_types import (
    CallToolAction,
    CallToolObservation,
    ListToolsAction,
)
from openenv.core.env_server.types import Action

# Support running as package or standalone
try:
    from .inventory_clone_environment import InventoryCloneEnvironment
except ImportError:
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    from inventory_clone_environment import InventoryCloneEnvironment


# ── Discriminated Union for MCP Actions ──
# MCPToolClient sends both ListToolsAction and CallToolAction via the
# same WebSocket "step" channel. This wrapper auto-dispatches to the
# correct concrete Action subclass based on the "type" discriminator.
_mcp_action_adapter = TypeAdapter(Union[ListToolsAction, CallToolAction])


class MCPAction(Action):
    """Discriminated-union action that deserialises to the correct MCP action."""

    @classmethod
    def model_validate(cls, data: Any, **kwargs: Any) -> Action:  # type: ignore[override]
        return _mcp_action_adapter.validate_python(data)


# ── Create the OpenEnv app ──
# create_app() generates the ENTIRE FastAPI application automatically.
app = create_app(
    InventoryCloneEnvironment,
    MCPAction,
    CallToolObservation,
    env_name="inventory_clone_env",
)


def main(host: str = "0.0.0.0", port: int = 9001):
    """
    Entry point for: uv run --project . server

    Starts the OpenEnv server on port 9000.
    """
    import uvicorn

    uvicorn.run(app, host=host, port=port)


if __name__ == "__main__":
    main()
