"""
Inventory Management API — FastAPI backend with session-scoped DB isolation.

Supports concurrent evaluation sessions:
  - Each session gets its own isolated SQLite database
  - Sessions are created/deleted via /sessions endpoints
  - The X-Session-ID header routes requests to the correct DB
  - If no header is provided, the default (shared) DB is used

Ports:
  - 8000: This API (products + orders CRUD + session management)
  - 9000: OpenEnv server (handled by server/app.py)
"""

import os
from contextlib import asynccontextmanager

from dotenv import load_dotenv
from fastapi import FastAPI

load_dotenv()

# Ensure data directory exists (for SQLite DBs)
os.makedirs(os.path.join(os.path.dirname(os.path.abspath(__file__)), "data"), exist_ok=True)

from database import init_db
from routers.products import router as products_router
from routers.orders import router as orders_router
from session_manager import session_manager

# Ensure all models are registered with Base.metadata before init_db() runs
import models  # noqa: F401


@asynccontextmanager
async def lifespan(app_instance: FastAPI):
    await init_db()
    yield
    await session_manager.cleanup_all()


app = FastAPI(
    title="Inventory Management API",
    version="0.4.0",
    description="Inventory CRUD API with per-session database isolation for concurrent evaluations.",
    lifespan=lifespan,
)

app.include_router(products_router)
app.include_router(orders_router)


# ── Health ──

@app.get("/health")
async def health():
    return {"status": "ok"}


# ── Session Management ──

@app.post("/sessions", status_code=201)
async def create_session(session_id: str):
    """
    Create a new evaluation session with an isolated database.

    The session_id is typically a UUID generated by the OpenEnv environment
    on reset(). All subsequent tool calls from that environment instance
    will include X-Session-ID: {session_id} to route to this DB.
    """
    sid = await session_manager.create_session(session_id)
    return {"session_id": sid, "status": "created"}


@app.get("/sessions")
async def list_sessions():
    """List all active evaluation sessions."""
    sessions = await session_manager.list_sessions()
    return {"sessions": sessions, "count": len(sessions)}


@app.delete("/sessions/{session_id}")
async def delete_session(session_id: str):
    """
    Delete a session and its isolated database.

    Called by the OpenEnv environment on close() to clean up.
    """
    deleted = await session_manager.delete_session(session_id)
    if deleted:
        return {"session_id": session_id, "status": "deleted"}
    return {"session_id": session_id, "status": "not_found"}


if __name__ == "__main__":
    import uvicorn

    port = int(os.getenv("API_PORT", "8000"))
    uvicorn.run("main:app", host="0.0.0.0", port=port)
