"""
OpenEnv HTTP/WebSocket Server for the Inventory Environment.

Uses OpenEnv's create_app() to auto-generate ALL server routes:
  - POST /reset        → Reset the environment
  - POST /step         → Execute an action
  - GET  /state        → Get current state
  - GET  /health       → Health check
  - WebSocket /ws      → Persistent WebSocket connection
  - GET  /schema       → Action/Observation JSON schemas
  - GET  /             → Web UI (auto-generated by OpenEnv!)

Concurrent Sessions:
  - MAX_CONCURRENT_ENVS controls how many simultaneous WebSocket sessions
    are allowed (default: 4). Each session gets its own InventoryEnvironment
    instance, which in turn creates a session-scoped database via the API.
  - Configured in inventory/.env (MAX_CONCURRENT_ENVS=4)

Usage:
    Docker (preferred): docker run -d --name inventory -p 8000:8000 -p 9000:9000 openenv-inventory
"""

import os
import sys
from pathlib import Path
from typing import Any, Union

from pydantic import TypeAdapter

from openenv.core.env_server.http_server import create_app
from openenv.core.env_server.mcp_types import (
    CallToolAction,
    CallToolObservation,
    ListToolsAction,
)
from openenv.core.env_server.types import Action

# Support running as package (from repo root) or standalone (from inventory/)
try:
    from .inventory_environment import InventoryEnvironment
except ImportError:
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    from inventory_environment import InventoryEnvironment


# ── Discriminated Union for MCP Actions ──
# The MCPToolClient sends both ListToolsAction and CallToolAction via the
# same WebSocket "step" channel.  OpenEnv's server calls
#   action_cls.model_validate(data)
# to deserialise the incoming message.  If we pass only CallToolAction,
# ListToolsAction messages cause a ValidationError.
#
# Solution: create a thin wrapper class whose model_validate() uses a
# Pydantic TypeAdapter to automatically dispatch to the right concrete
# Action subclass based on the "type" discriminator field.
_mcp_action_adapter = TypeAdapter(Union[ListToolsAction, CallToolAction])


class MCPAction(Action):
    """Discriminated-union action that deserialises to the correct MCP action."""

    @classmethod
    def model_validate(cls, data: Any, **kwargs: Any) -> Action:  # type: ignore[override]
        return _mcp_action_adapter.validate_python(data)


# ── Config (read directly from .env) ──
from dotenv import load_dotenv
load_dotenv(os.path.join(os.path.dirname(__file__), "..", ".env"))

MAX_CONCURRENT_ENVS = int(os.getenv("MAX_CONCURRENT_ENVS", "4"))
OPENENV_PORT = int(os.getenv("OPENENV_PORT", "9000"))

# ── THIS IS THE KEY LINE ──
# create_app() generates the ENTIRE FastAPI application automatically:
# - HTTP endpoints (/reset, /step, /state, /health, /schema)
# - WebSocket endpoint (/ws) for persistent connections
# - Web UI for interactive testing
# - Swagger/OpenAPI docs
#
# Arguments:
#   InventoryEnvironment  → Your environment CLASS (not instance!)
#   MCPAction             → Discriminated union so BOTH list_tools AND call_tool work
#   CallToolObservation   → The observation type (MCP tool results)
#   env_name              → Name shown in the UI and docs
#   max_concurrent_envs   → How many simultaneous sessions allowed
app = create_app(
    InventoryEnvironment,
    MCPAction,
    CallToolObservation,
    env_name="inventory_env",
    max_concurrent_envs=MAX_CONCURRENT_ENVS,
)


def main():
    """
    Entry point for direct execution.

    Starts the OpenEnv server on the configured OPENENV_PORT (default 9000).
    Make sure the Inventory API is already running on API_PORT (default 8000).
    """
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=OPENENV_PORT)


if __name__ == "__main__":
    main()
