"""
OpenEnv HTTP/WebSocket Server for the Inventory Environment.

This file uses OpenEnv's create_app() to auto-generate ALL server routes:
  - POST /reset        → Reset the environment
  - POST /step         → Execute an action
  - GET  /state        → Get current state
  - GET  /health       → Health check
  - WebSocket /ws      → Persistent WebSocket connection
  - GET  /schema       → Action/Observation JSON schemas
  - GET  /             → Web UI (auto-generated by OpenEnv!)

Instead of manually defining 7+ routes like we did before,
create_app() does it ALL in ONE line.

Usage:
    # Start the server:
    cd /home/kdemon/Clients/huzzle/inventory-api
    python server/app.py

    # Or with uvicorn directly:
    uvicorn server.app:app --host 0.0.0.0 --port 9000
"""

from typing import Any, Dict, Union

from pydantic import TypeAdapter

# Support both in-repo and standalone imports
try:
    from openenv.core.env_server.http_server import create_app
    from openenv.core.env_server.mcp_types import (
        CallToolAction,
        CallToolObservation,
        ListToolsAction,
    )
    from openenv.core.env_server.types import Action
    from .inventory_environment import InventoryEnvironment
except ImportError:
    from openenv.core.env_server.http_server import create_app
    from openenv.core.env_server.mcp_types import (
        CallToolAction,
        CallToolObservation,
        ListToolsAction,
    )
    from openenv.core.env_server.types import Action

    import sys
    from pathlib import Path
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    from inventory_environment import InventoryEnvironment


# ── Discriminated Union for MCP Actions ──
# The MCPToolClient sends both ListToolsAction and CallToolAction via the
# same WebSocket "step" channel.  OpenEnv's server calls
#   action_cls.model_validate(data)
# to deserialise the incoming message.  If we pass only CallToolAction,
# ListToolsAction messages cause a ValidationError.
#
# Solution: create a thin wrapper class whose model_validate() uses a
# Pydantic TypeAdapter to automatically dispatch to the right concrete
# Action subclass based on the "type" discriminator field.
_mcp_action_adapter = TypeAdapter(Union[ListToolsAction, CallToolAction])


class MCPAction(Action):
    """Discriminated-union action that deserialises to the correct MCP action."""

    @classmethod
    def model_validate(cls, data: Any, **kwargs: Any) -> Action:  # type: ignore[override]
        if isinstance(data, dict):
            return _mcp_action_adapter.validate_python(data)
        return _mcp_action_adapter.validate_python(data)


# ── THIS IS THE KEY LINE ──
# create_app() generates the ENTIRE FastAPI application automatically:
# - HTTP endpoints (/reset, /step, /state, /health, /schema)
# - WebSocket endpoint (/ws) for persistent connections
# - Web UI for interactive testing
# - Swagger/OpenAPI docs
#
# Arguments:
#   InventoryEnvironment  → Your environment CLASS (not instance!)
#   MCPAction             → Discriminated union so BOTH list_tools AND call_tool work
#   CallToolObservation   → The observation type (MCP tool results)
#   env_name              → Name shown in the UI and docs
app = create_app(
    InventoryEnvironment,
    MCPAction,
    CallToolObservation,
    env_name="inventory_env",
)


def main():
    """
    Entry point for direct execution.

    Starts the OpenEnv server on the configured OPENENV_PORT (default 9000).
    Make sure the Inventory API is already running on API_PORT (default 8000).
    """
    import uvicorn
    from config import OPENENV_PORT
    uvicorn.run(app, host="0.0.0.0", port=OPENENV_PORT)


if __name__ == "__main__":
    main()
