"""
Inventory Clone Environment Client — extends OpenEnv's MCPToolClient.

This was generated by `openenv init inventory_clone` and then customized
from the default typed EnvClient to use MCPToolClient (tool-based pattern).

Usage:
    >>> from inventory_clone.client import InventoryCloneEnv
    >>>
    >>> with InventoryCloneEnv(base_url="http://localhost:9000") as env:
    ...     env.reset()
    ...     tools = env.list_tools()
    ...     result = env.call_tool("list_products", active_only=True)
"""

from openenv.core.mcp_client import MCPToolClient


class InventoryCloneEnv(MCPToolClient):
    """
    Client for the Inventory Clone OpenEnv Environment.

    Inherits from MCPToolClient which provides:
      list_tools(), call_tool(), reset(), step(), state()
    """

    pass
